spring.application.name=FastFoodESI
spring.datasource.url=jdbc:h2:file:C:/Users/Usuario/Documents/GitHub/iw2025-2026-FastFoodESI/data/fastfooddb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true