spring.application.name=FastFoodESI
spring.datasource.url=jdbc:h2:file:./data/fastfooddb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=SA
spring.datasource.password=
spring.h2.console.enabled=true
# PERSISTENCIA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# CARGA DE DATOS
# always la PRIMERA vez para cargar tu data.sql.
# never las siguientes veces para no duplicar datos y usar lo guardado.
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
