spring.application.name=FastFoodESI
# Configuración de la Base de Datos H2 (en memoria)
spring.datasource.url=jdbc:h2:mem:fastfooddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Para que la consola de H2 esté disponible en la URL /h2-console
spring.h2.console.enabled=true

# Para que Spring Data JPA cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update